project:
  type: website

website:
  title: "Catie Wiener"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: https://ktwiener.github.io/ispe-simulation-workshop/
        text: ISPE Simulation Workshop
      - href: Wiener_CV_apr26.pdf
        text: CV
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



