project:
  type: website

website:
  title: "Catie Wiener"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Wiener_CV_apr25.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



